
const countryCodes = {
  "American": "US",
  "Argentine": "AR",
  "Australia": "AU",
  "Australian": "AU",
  "Austria": "AT",
  "Austrian": "AT",
  "Azerbaijan": "AZ",
  "Bahrain": "BH",
  "Belgium": "BE",
  "Belgian": "BE",
  "Brazil": "BR",
  "Brazilian": "BR",
  "British": "GB",
  "Georgia": "GE",
  "Canada": "CA",
  "Canadian": "CA",
  "China": "CN",
  "Chinese": "CN",
  "Danish": "DK",
  "Dutch": "NL",
  "France": "FR",
  "French": "FR",
  "Finnish": "FI",
  "Germany": "DE",
  "German": "DE",
  "Hungary": "HU",
  "Italy": "IT",
  "Italian": "IT",
  "Irish":"IE",
  "India":"IN",
  "Japan": "JP",
  "Japanese": "JP",
  "Mexican": "MX",
  "Mexico": "MX",
  "Monaco": "MC",
  "Monegasque": "MC",
  "Portugal": "PT",
  "Portuguese":"PT",
  "Netherlands": "NL",
  "New Zealander": "NZ",
  "Qatar": "QA",
  "Russia": "RU",
  "Saudi Arabia": "SA",
  "Singapore": "SG",
  "Spain": "ES",
  "Spanish": "ES",
  "Swiss": "CH",
  "Thai": "TH",
  "UAE": "AE",
  "UK": "GB",
  "USA": "US",
  "Vietnam": "VN",
  "Vietnamese": "VN",
  "Turkey":"TR",
  "Switzerland":"CH",
  "Argentina":"AR",
  "Morocco":"MA",
  "South Africa": "ZA",
  "South African": "ZA",
  "Sweden": "SE",
  "Swedish":"SE",
  "San Marino": "SM",
  "Malaysia": "MY",
  "Korea":"KR",
  "Uruguayan":"UY",
  "East German":"DD",
  "Venezuelan":"VE",
  "Rhodesian":"ZW", // rhodesia renamed zimbabwe
  "Liechtensteiner":"LI",
  "Colombian":"CO",
  "Polish":"PL",
  "Russian":"RU",
  "Indonesian":"ID",
  "Indian":"IN",
  "Hungarian":"HU",
  "Malaysian":"MY",
  "Czech":"CZ",
  "Chilean":"CL",
  "Hong Kong":"HK",
};

const countryCodes3 = {
  "US": "USA",
  "AR": "ARG",
  "AU": "AUS",
  "AT": "AUT",
  "AZ": "AZE",
  "BH": "BHR",
  "BE": "BEL",
  "BR": "BRA",
  "CA": "CAN",
  "CH": "CHE",
  "CN": "CHN",
  "DK": "DNK",
  "FI": "FIN",
  "FR": "FRA",
  "DE": "DEU",
  "GB": "GBR",
  "HU": "HUN",
  "IE":"IRE",
  "IN":"IND",
  "IT": "ITA",
  "JP": "JPN",
  "MX": "MEX",
  "MC": "MCO",
  "NL": "NLD",
  "NZ": "NZL",
  "QA": "QAT",
  "RU": "RUS",
  "SA": "SAU",
  "SG": "SGP",
  "ES": "ESP",
  "TH": "THA",
  "AE": "ARE",
  "VN": "VNM",
  "PT":"POR",
  "TR":"TUR",
  "MA": "MAR",
  "ZA": "ZAF",
  "SE": "SWE",
  "SM": "SMR", 
  "MY":"MYS",
  "KR":"KOR",
  "UY":"URY",
  "DD":"DDR",
  "VE":"VEN",
  "ZW":"ZWE",
  "CO":"COL",
  "LI":"LIE",
  "PL":"POL",
  "RU":"RUS",
  "ID":"IDN",
  "IN":"IND",
  "HU":"HUN",
  "MY":"MYS",
  "CZ":"CZE",
  "CL":"CHL",
  "HK":"HKG",
};

export function countryInfoFor(country) {
  let countryCode = countryCodes[country]
  if (countryCode === undefined) {
    throw new Error(`Country code not found for ${country}`)
  }
  const code3 = countryCodes3[countryCode]
  if (code3 === undefined) {
    throw new Error(`Country code3 not found for ${countryCode}`)
  }
  const codePoints = countryCode.toUpperCase().split("").map((char) => 127397 + char.charCodeAt(0));
  return {
    code: countryCode,
    flag: String.fromCodePoint(...codePoints),
    code3: code3
   };
}